# Site settings
title: "Kayla Martinez"
email: "kaylaann88@gmail.com"
description: > # My Professional Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site



github_username:

# Build settings
markdown: kramdown
